// ============================================================
// models/LeaveBalance.js
// Author: Karen (karen-branch)
// ============================================================

module.exports = (sequelize, DataTypes) => {
  const LeaveBalance = sequelize.define(
    'LeaveBalance',
    {
      // Unique ID for each record (auto-generated by Sequelize)
      id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },

      // The year the leave balance applies to (e.g., 2025)
      year: {
        type: DataTypes.INTEGER,
        allowNull: false,
        defaultValue: new Date().getFullYear(),
      },

      // Number of leave days remaining for the employee
      remainingDays: {
        type: DataTypes.FLOAT,
        allowNull: false,
        defaultValue: 0,
      },

      // Leave days carried over from previous financial year
      previousYearDays: {
        type: DataTypes.FLOAT,
        allowNull: true,
        defaultValue: 0,
      },

      // Default annual leave entitlement (e.g., 20 days)
      defaultDays: {
        type: DataTypes.FLOAT,
        allowNull: false,
        defaultValue: 20,
      },

      // Foreign key for employee (User)
      userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },

      // Foreign key for leave type (e.g., Annual, Sick)
      leaveTypeId: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
    },
    {
      tableName: 'LeaveBalances',
      timestamps: true, // Adds createdAt and updatedAt automatically
    }
  );

  // ============================================================
  // ASSOCIATIONS
  // Each LeaveBalance belongs to one User and one LeaveType
  // ============================================================
  LeaveBalance.associate = (models) => {
    LeaveBalance.belongsTo(models.User, {
      foreignKey: 'userId',
      as: 'user',
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
    });

    LeaveBalance.belongsTo(models.LeaveType, {
      foreignKey: 'leaveTypeId',
      as: 'leaveType',
      onDelete: 'CASCADE',
      onUpdate: 'CASCADE',
    });
  };

  return LeaveBalance;
};

      allowNull: false,
      references: {
        model: 'leave_types',
        key: 'id'
      }
    },
    year: {
      type: DataTypes.INTEGER,
      allowNull: false,
      comment: 'Financial year (e.g., 2024 for FY 2024-25)'
    },
    totalDays: {
      type: DataTypes.DECIMAL(4, 1),
      allowNull: false,
      defaultValue: 0,
      comment: 'Total allocated days for the year'
    },
    usedDays: {
      type: DataTypes.DECIMAL(4, 1),
      allowNull: false,
      defaultValue: 0,
      comment: 'Days used in the current year'
    },
    remainingDays: {
      type: DataTypes.DECIMAL(4, 1),
      allowNull: false,
      defaultValue: 0,
      comment: 'Days remaining for the year'
    },
    carriedOverDays: {
      type: DataTypes.DECIMAL(4, 1),
      allowNull: false,
      defaultValue: 0,
      comment: 'Days carried over from previous year'
    },
    maxCarryOver: {
      type: DataTypes.DECIMAL(4, 1),
      allowNull: false,
      defaultValue: 5,
      comment: 'Maximum days that can be carried over'
    },
    isActive: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true
    },
    lastUpdatedBy: {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'users',
        key: 'id'
      },
      comment: 'Admin who last updated this balance'
    },
    notes: {
      type: DataTypes.TEXT,
      allowNull: true,
      comment: 'Admin notes for balance adjustments'
    }
  }, {
    tableName: 'leave_balances',
    timestamps: true,
    indexes: [
      {
        unique: true,
        fields: ['userId', 'leaveTypeId', 'year']
      }
    ]
  });

  return LeaveBalance;
}; 
